import Head from 'next/head'
import { Provider } from 'react-redux'
import StartingComponent from '../components/StartingComponent'
import Toast from '../components/toast/Toast'
import Footer from '../layout/footer/Footer'
import Header from '../layout/header/Header'
import store from '../redux/store'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {

  return (
    <div className='relative'>
     <Head>
      <title>Balushai Ecommerce</title>
      <meta name="description" content="Generated by create next app" />
      <link  rel="icon" href="/images/logo.jpg" />
    </Head>
     <Provider store={store}>
        <Header/>
          <main>
            <Component {...pageProps} />
          </main>
        <Footer/>
        <Toast/>
        <StartingComponent/>
     </Provider>
    </div>
  )
}

export default MyApp
