import Head from 'next/head'
import HeroSection from '../components/home/HeroSection'
import Banner from '../components/home/mobile/Banner'
import HeroCategory from '../components/home/mobile/HeroCategory'
import ProductCard from '../components/home/ProductCard'
import ProductSection from '../components/home/ProductSection'
import SuperDealsSection from '../components/home/SuperDealsSection'
import Footer from '../layout/footer/Footer'
import Header from '../layout/header/Header'
import MobileFooter from '../layout/mobile/footer/MobileFooter'
import MobileHeader from '../layout/mobile/header/MobileHeader'
import Link from 'next/link'
import { AllProducts } from '../adapters/product'
import { setUserData } from '../redux'
import { useDispatch } from 'react-redux'
import { getUserData } from '../adapters/user'

export default function Home({products}) {
  console.log(products)
  return (
    <div>
      <Head>
        <title>Balushai Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link  rel="icon" href="/images/logo.jpg" />
      </Head>
      
      <div className='hidden sm:block'>
        <HeroSection/>
        {/* <SuperDealsSection/> */}
        <ProductSection productList={products}/>
      </div>
      <div className='sm:hidden'>
        <MobileHeader/>
        <HeroCategory/>
        <Banner/>
        <MobileFooter/>
      </div>

      
    </div>
  )
}

export async function getStaticProps(context) {
  const response = await AllProducts()
  // const userInfo = await getUserData()
  // console.log("userInfo: ", userInfo)
  return {
    props: {
      products: response.data
    }, // will be passed to the page component as props
    revalidate: 10,
  }
}

